site_name: The Path (AI-Pi)
site_url: https://materdev.github.io/thepath-ai_pi/
repo_url: https://github.com/MaterDev/thepath-ai_pi
repo_name: MaterDev/thepath-ai_pi

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.indexes
  - navigation.instant
  - navigation.tracking
  - toc.follow
  - search.suggest
  - search.highlight
  - navigation.tabs.sticky
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
docs_dir: docs
site_dir: site
nav:
- Home: index.md
- Overview:
  - Project Scope: overview/project-scope.md
  - Research Objectives: overview/research-objectives.md
- Logs:
  - Overview: meta/logs/index.md
  - January 15, 2025: meta/logs/2025-01-15.md
  - January 13, 2025: meta/logs/2025-01-13.md
  - January 09, 2025: meta/logs/2025-01-09.md
  - January 08, 2025: meta/logs/2025-01-08.md
- Development:
  - Setup: meta/implementation/setup/project-setup.md
  - Planning:
    - Phase 1:
      - Overview: meta/phase1/index.md
      - Project Setup: meta/phase1/1-project-setup.md
      - Game State: meta/phase1/2-game-state.md
      - Communication: meta/phase1/3-communication.md
      - AI Integration: meta/phase1/4-ai-integration.md
      - Turn System: meta/phase1/5-turn-system.md
  - AI Development Index: AI_DEVELOPMENT_INDEX.md
  - Style Guide: meta/style-guide.md
- Technical:
  - Dependencies: technical/dependencies.md
  - Hardware: technical/hardware/configuration.md
- Character Classes:
  - Conjuror: character_classes/conjuror.md
  - Crystal Vanguard: character_classes/crystal_vanguard.md
  - Zealot: character_classes/zealot.md
  - Wraithwood Seer: character_classes/wraithwood_seer.md
  - Primal Shifter: character_classes/primal_shifter.md
  - The Blessed: character_classes/the_blessed.md
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- admonition
- footnotes
- toc:
    permalink: true
    title: On this page
- attr_list
- md_in_html
- def_list
plugins:
- search
- awesome-pages
- tags
