site_name: The Path (AI-Pi)
site_description: Documentation for The Path (AI-Pi) project
site_author: MaterDev
site_url: https://materdev.github.io/thepath-ai_pi/
repo_url: https://github.com/MaterDev/thepath-ai_pi
repo_name: MaterDev/thepath-ai_pi
theme:
  name: material
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
- stylesheets/extra.css
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- tables
- footnotes
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- toc:
    permalink: true
    title: On this page
plugins:
- search
- awesome-pages
docs_dir: docs
site_dir: site
nav:
- Home: index.md
- World:
  - Cultural Foundations: world/cultural_foundations.md
- Combat System:
  - Overview: combat_system/balance_and_meta.md
  - Character Classes: combat_system/classes.md
- Implementation:
  - Setup:
    - Project Setup: implementation/setup/project-setup.md
    - Development Environment: implementation/setup/development-environment.md
  - Architecture:
    - System Design: implementation/architecture/system-design.md
    - Data Flow: implementation/architecture/data-flow.md
  - AI:
    - Overview: implementation/ai/overview.md
    - Models: implementation/ai/models.md
    - Training: implementation/ai/training.md
  - Hardware:
    - Requirements: implementation/hardware/requirements.md
    - Optimization: implementation/hardware/optimization.md
- Meta:
  - Development Guidelines: meta/development-guidelines.md
  - Documentation Standards: meta/documentation-standards.md
  - Style Guide: meta/style-guide.md
  - Analysis:
    - Documentation Analysis: meta/analysis/documentation-analysis.md
  - Logs:
    - 2025-01-13: meta/logs/2025-01-13.md
    - 2025-01-09: meta/logs/2025-01-09.md
- AI Development Index: AI_DEVELOPMENT_INDEX.md
